### ISSUE TITLE
Doesn't work with ruby 2.x

### ISSUE THREAD

**Issue by sammcj** [diasjorge/redmine-cli#11]
Looks like it relies on ruby-debug which I don't think exists anymore.

```
~  % redmine install
/Users/samm/.rvm/gems/ruby-2.2.3/gems/activesupport-3.0.20/lib/active_support/values/time_zone.rb:272: warning: circular argument reference - now
Warning: No .redmine file was found in your home directory. Use "redmine install" to create one.
/Users/samm/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- ruby-debug (LoadError)
    from /Users/samm/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/samm/.rvm/gems/ruby-2.2.3/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `block in require'
    from /Users/samm/.rvm/gems/ruby-2.2.3/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from /Users/samm/.rvm/gems/ruby-2.2.3/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:597:in `new_constants_in'
    from /Users/samm/.rvm/gems/ruby-2.2.3/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Users/samm/.rvm/gems/ruby-2.2.3/gems/activesupport-3.0.20/lib/active_support/dependencies.rb:242:in `require'
    from /Users/samm/.rvm/gems/ruby-2.2.3/gems/redmine-cli-0.1.6/lib/redmine-cli/cli.rb:7:in `<top (required)>'
    from /Users/samm/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/samm/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/samm/.rvm/gems/ruby-2.2.3/gems/redmine-cli-0.1.6/bin/redmine:7:in `<top (required)>'
    from /Users/samm/.rvm/gems/ruby-2.2.3/bin/redmine:23:in `load'
    from /Users/samm/.rvm/gems/ruby-2.2.3/bin/redmine:23:in `<main>'
    from /Users/samm/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
    from /Users/samm/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by GSI** [comment]
+1

**Comment by GSI** [comment]
After removing `require 'ruby-debug'` from **lib/redmine-cli/cli.rb**, the gem works.

However, it's pretty destructive: I ran `redmine update 123` and it cleared some custom fields from the according issue.

**Comment by diasjorge** [comment]
Hi @GSI I haven't used this project in many years. I invite you to contribute to the project if you find it useful for you.
